import { cn } from "@/lib/utils";
import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "./globals.css";
import Providers from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gity App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          inter.className,
          "antialiased bg-app-backgound min-h-dvh",
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
