import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Providers from "@/providers";
import "@/lib/global-setup";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gity App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="manifest"
          href="/manifest.json"
          crossOrigin="use-credentials"
        />
        <link rel="apple-touch-icon" href="/app-icon.png" />
        <meta name="theme-color" content="#0093BC" />
      </head>
      <body
        className={cn(
          inter.className,
          "antialiased bg-app-backgound min-h-dvh",
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
